from .diagnosis_admin import SubjectDiagnosisAdmin
from .diagnostic_tests_admin import SubjectDiagnosticTestsAdmin
from .drug_susceptibility_admin import SubjectDrugSusceptibilityAdmin
from .enrollment_admin import SubjectEnrollmentAdmin
from .respiratory_sample_admin import SubjectRespiratorySampleAdmin
from .subject_visit_admin import SubjectVisitAdmin
