# Generated by Django 4.2 on 2024-01-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edcs_subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrespiratorysample",
            name="test_not_repeated_reason",
            field=models.CharField(
                choices=[
                    ("N/A", "Not applicable"),
                    ("sample_lost ", "sample lost "),
                    ("not_enough_sample", "not enough sample left"),
                    ("OTHER", "Other"),
                ],
                max_length=45,
                verbose_name="If No, specify reasons",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrespiratorysample",
            name="truenat_test_not_repeated_reason",
            field=models.CharField(
                choices=[
                    ("N/A", "Not applicable"),
                    ("sample_lost ", "sample lost "),
                    ("not_enough_sample", "not enough sample left"),
                    ("OTHER", "Other"),
                ],
                max_length=45,
                verbose_name="If No, specify reasons",
            ),
        ),
        migrations.AlterField(
            model_name="respiratorysample",
            name="test_not_repeated_reason",
            field=models.CharField(
                choices=[
                    ("N/A", "Not applicable"),
                    ("sample_lost ", "sample lost "),
                    ("not_enough_sample", "not enough sample left"),
                    ("OTHER", "Other"),
                ],
                max_length=45,
                verbose_name="If No, specify reasons",
            ),
        ),
        migrations.AlterField(
            model_name="respiratorysample",
            name="truenat_test_not_repeated_reason",
            field=models.CharField(
                choices=[
                    ("N/A", "Not applicable"),
                    ("sample_lost ", "sample lost "),
                    ("not_enough_sample", "not enough sample left"),
                    ("OTHER", "Other"),
                ],
                max_length=45,
                verbose_name="If No, specify reasons",
            ),
        ),
    ]
