# Generated by Django 4.2 on 2024-01-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edcs_subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentcrf",
            name="other_disease_specify",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diabetes_mellitus", "Diabetes Mellitus"),
                    ("hypertension", "Hypertension"),
                    ("COPD", "Chronic obstructive pulmonary disease (COPD)"),
                    ("malignancy", "Malignancy"),
                    ("heart_disease", "Heart disease"),
                    ("CKD", "Chronic kidney disease (CKD)"),
                    ("organ_transplant", "Organ transplant"),
                    ("OTHER", "Other"),
                ],
                max_length=45,
                null=True,
                verbose_name="If yes, to other relevant disease/medical condition?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalenrollmentcrf",
            name="other_disease_specify",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diabetes_mellitus", "Diabetes Mellitus"),
                    ("hypertension", "Hypertension"),
                    ("COPD", "Chronic obstructive pulmonary disease (COPD)"),
                    ("malignancy", "Malignancy"),
                    ("heart_disease", "Heart disease"),
                    ("CKD", "Chronic kidney disease (CKD)"),
                    ("organ_transplant", "Organ transplant"),
                    ("OTHER", "Other"),
                ],
                max_length=45,
                null=True,
                verbose_name="If yes, to other relevant disease/medical condition?",
            ),
        ),
    ]
