# Generated by Django 4.2 on 2024-01-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edcs_subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_amikacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_bedaquiline_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_clofazimine_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_cycloserine_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_delamanid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_ethambutol_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_ethionamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_imipenem_cilastatin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_isoniazid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_levofloxacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_linezolid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_meropenem_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_moxifloxacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_para_aminosalicylic_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_prothionamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_pyrazinamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_rifampicin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_streptomycin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="nanopore_terizidone_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_amikacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_bedaquiline_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_clofazimine_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_cycloserine_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_delamanid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_ethambutol_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_ethionamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_imipenem_cilastatin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_isoniazid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_levofloxacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_linezolid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_meropenem_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_moxifloxacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_para_aminosalicylic_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_prothionamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_pyrazinamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_rifampicin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_streptomycin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="drugsusceptibilitytests",
            name="phenotypic_terizidone_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_amikacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_bedaquiline_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_clofazimine_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_cycloserine_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_delamanid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_ethambutol_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_ethionamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_imipenem_cilastatin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_isoniazid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_levofloxacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_linezolid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_meropenem_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_moxifloxacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_para_aminosalicylic_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_prothionamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_pyrazinamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_rifampicin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_streptomycin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="nanopore_terizidone_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_amikacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_bedaquiline_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_clofazimine_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_cycloserine_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_delamanid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_ethambutol_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_ethionamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_imipenem_cilastatin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_isoniazid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_levofloxacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_linezolid_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_meropenem_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_moxifloxacin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_para_aminosalicylic_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_prothionamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_pyrazinamide_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_rifampicin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_streptomycin_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
        migrations.AlterField(
            model_name="historicaldrugsusceptibilitytests",
            name="phenotypic_terizidone_mic",
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name="MIC"),
        ),
    ]
