# Generated by Django 4.2 on 2024-01-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edcs_subject", "0002_alter_enrollmentcrf_other_disease_specify_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentcrf",
            name="resp_sample",
            field=models.CharField(
                choices=[
                    ("yes_two", "Yes, two samples were collected"),
                    ("no_one", "No, one sample was collected"),
                    ("No", "No, no such samples were collected "),
                ],
                max_length=45,
                verbose_name="After TB was confirmed by a rapid molecular test, were two additional respiratory samples collected?",
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentcrf",
            name="resp_sample_seq_date",
            field=models.DateField(
                blank=True,
                help_text="only if two samples were collected",
                null=True,
                verbose_name="Date of Sample for sequencing collection",
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentcrf",
            name="resp_sample_type_seq",
            field=models.CharField(
                blank=True,
                help_text="only if two samples were collected",
                max_length=200,
                null=True,
                verbose_name="Sample type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalenrollmentcrf",
            name="resp_sample",
            field=models.CharField(
                choices=[
                    ("yes_two", "Yes, two samples were collected"),
                    ("no_one", "No, one sample was collected"),
                    ("No", "No, no such samples were collected "),
                ],
                max_length=45,
                verbose_name="After TB was confirmed by a rapid molecular test, were two additional respiratory samples collected?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalenrollmentcrf",
            name="resp_sample_seq_date",
            field=models.DateField(
                blank=True,
                help_text="only if two samples were collected",
                null=True,
                verbose_name="Date of Sample for sequencing collection",
            ),
        ),
        migrations.AlterField(
            model_name="historicalenrollmentcrf",
            name="resp_sample_type_seq",
            field=models.CharField(
                blank=True,
                help_text="only if two samples were collected",
                max_length=200,
                null=True,
                verbose_name="Sample type",
            ),
        ),
    ]
