# Generated by Django 4.2 on 2024-01-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edcs_subject", "0004_alter_diagnostictests_culture_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosiscrf",
            name="TB_dx_made",
            field=models.CharField(
                choices=[
                    ("N/A", "Not applicable"),
                    ("signs_symptoms_only", "Based on clinical signs and symptoms only "),
                    (
                        "signs_symptoms_bacteriology",
                        "Based a combination of signs, symptoms and bacteriology",
                    ),
                    ("OTHER", "Other"),
                ],
                max_length=45,
                verbose_name="How was the TB diagnosis made?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnosiscrf",
            name="TB_dx_made",
            field=models.CharField(
                choices=[
                    ("N/A", "Not applicable"),
                    ("signs_symptoms_only", "Based on clinical signs and symptoms only "),
                    (
                        "signs_symptoms_bacteriology",
                        "Based a combination of signs, symptoms and bacteriology",
                    ),
                    ("OTHER", "Other"),
                ],
                max_length=45,
                verbose_name="How was the TB diagnosis made?",
            ),
        ),
    ]
