# Generated by Django 4.2 on 2024-02-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edcs_subject", "0005_alter_diagnosiscrf_tb_dx_made_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosiscrf",
            name="TB_dx_xpert_truenat_nga",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=45,
                verbose_name="On what test result(s) was the bacteriological diagnosis based on Xpert/Truenat on sputum/NGA?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnosiscrf",
            name="TB_dx_xpert_truenat_nga",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=45,
                verbose_name="On what test result(s) was the bacteriological diagnosis based on Xpert/Truenat on sputum/NGA?",
            ),
        ),
    ]
